[2024-07-19T21:45:35.590+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T21:45:35.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-19T21:45:34.643025+00:00 [queued]>
[2024-07-19T21:45:35.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-19T21:45:34.643025+00:00 [queued]>
[2024-07-19T21:45:35.617+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-19T21:45:35.628+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-07-19 21:45:34.643025+00:00
[2024-07-19T21:45:35.635+0000] {standard_task_runner.py:64} INFO - Started process 84 to run task
[2024-07-19T21:45:35.638+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-07-19T21:45:34.643025+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpdzs69wvl']
[2024-07-19T21:45:35.640+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask reddit_extraction
[2024-07-19T21:45:35.676+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-19T21:45:34.643025+00:00 [running]> on host aa0946d1cd0d
[2024-07-19T21:45:35.744+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nopega' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T21:45:34.643025+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T21:45:34.643025+00:00'
[2024-07-19T21:45:35.745+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T21:45:35.760+0000] {logging_mixin.py:188} INFO - connect to reddit!
[2024-07-19T21:45:36.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T21:45:36.957+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 11, in reddit_pipeline
    post_df = transform_data(post_df)
  File "/opt/airflow/etls/reddit_etl.py", line 41, in transform_data
    post_df['selftext'] = post_df['selftext'].astype(int)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5912, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 419, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 580, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1292, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1237, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1154, in astype_nansafe
    return lib.astype_intsafe(arr, dtype)
  File "pandas/_libs/lib.pyx", line 668, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: "tl;dr: Can you be a data enginner without coding skills and just use no or low-code tools like Alteryx to do the job?\n\nI've been in analytics and data visualization for well over 10 years. The tool
[2024-07-19T21:45:36.974+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-07-19T21:45:34.643025+00:00, execution_date=20240719T214534, start_date=20240719T214535, end_date=20240719T214536
[2024-07-19T21:45:36.982+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task reddit_extraction (invalid literal for int() with base 10: "tl;dr: Can you be a data enginner without coding skills and just use no or low-code tools like Alteryx to do the job?\n\nI've been in analytics and data visualization for well over 10 years. The tool; 84)
[2024-07-19T21:45:37.014+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T21:45:37.031+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T21:45:37.032+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
